### ISSUE TITLE
Error: Can't resolve 'sqlite3-opfs-async-proxy.js'

### ISSUE THREAD

**Issue by saeedesmaili** [nalgeon/sqlean.js#2]
I installed the package using `npm install @antonz/sqlean` and tried using it in my react project with:

```js
import sqlite3InitModule from '@antonz/sqlean';
```

But I get the following error:
```
Compiled with problems:
×
ERROR in ./node_modules/@antonz/sqlean/dist/sqlean.mjs 5779:20-87
Module not found: Error: Can't resolve 'sqlite3-opfs-async-proxy.js' in '<my-project>/node_modules/@antonz/sqlean/dist'
```

**Comment by nalgeon** [comment]
Sorry, can't help you with that. Try using the official package [@sqlite.org/sqlite-wasm](https://www.npmjs.com/package/@sqlite.org/sqlite-wasm).
